
on:
  pull_request:
    branches: [ main ]

concurrency:
  group: plan-run-${{ github.head_ref }}
  #group: plan-run
  #cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo "Running one-line script"
          sleep 2m
          echo "Finish running script"

      - name: Run a multi-line script
        run: |
          sleep 2m
          echo "finish running multi-line script"
